apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recipes-service-autoscaler
  namespace: api
  labels:
    fluxcd.io/automated: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recipes-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
