apiVersion: v1
kind: Service
metadata:
  name: recipes-service
  namespace: api
  labels:
    fluxcd.io/automated: "true"
spec:
  selector:
    app: recipes-service
  ports:
  - port: 3000
    name: http
  type: ClusterIP

