apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: sundial-system
data:
  NAMESPACE: "api"
  PROMETHEUS_HOST: "10.245.123.199"
  PROMETHEUS_PORT: "9090"
  PROMETHEUS_RANGE_QUERY_PATH: "/api/v1/query_range"
  INTERVAL: "30000"
  STEP: "1s"
  DATA_PATH: "/data"
  DATA_FILE: "training.csv"
