apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: api
  labels:
    app: {{ .Release.Name }}
    version: v1.0.0
    servicemode: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: v1.0.0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: v1.0.0
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: registry.digitalocean.com/newlinelabs/sundial-recipe-service:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: FIBONACCI
          value: "1000"
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 300m
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false