apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: api
spec:
  selector:
    app: {{ .Release.Name }}-service
  ports:
  - port: 3000
    name: http
  type: ClusterIP

