kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sundial-hose-storage
  namespace: sundial
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
